#!/usr/bin/env python3
"""Drive the SO-101 follower smoothly to a HOME pose.

Used between phases of the autonomous sequence so each ACT policy starts
from the same pose distribution it was trained on.

Reads HOME from scripts/home_pose.json (generated by capture_home.py).

Usage:
    .conda/bin/python scripts/go_home.py
    .conda/bin/python scripts/go_home.py --duration 4.0  # take 4 seconds
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOME_JSON = ROOT / "scripts" / "home_pose.json"

# Hardware port (verified May 1, 2026)
FOLLOWER_PORT = "/dev/tty.usbmodem5B141124491"
ROBOT_ID = "so101_follower_main"

# Safe step size — same conservative limit we used for recording.
MAX_STEP_DEG = 1.5  # deg per command frame
HZ = 30  # command rate


def load_home(task: str | None = None) -> dict[str, float]:
    """Load HOME pose. If `task` is given, returns that task's natural start
    pose; otherwise returns the canonical home (= start of pick task)."""
    if not HOME_JSON.exists():
        raise FileNotFoundError(
            f"{HOME_JSON} not found. Run scripts/capture_home.py first."
        )
    data = json.loads(HOME_JSON.read_text())
    if task is None:
        return data["canonical_home"]
    if task not in data["per_task_starts"]:
        raise KeyError(
            f"Unknown task '{task}'. Available: {list(data['per_task_starts'].keys())}"
        )
    return data["per_task_starts"][task]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--task", choices=["pick", "plug", "pour"], default=None,
                        help="Drive to this task's natural starting pose. "
                             "Default: canonical home (= pick start).")
    parser.add_argument("--duration", type=float, default=3.0,
                        help="Seconds to take reaching HOME (default 3.0).")
    parser.add_argument("--quiet", action="store_true",
                        help="Suppress progress output.")
    parser.add_argument("--release-on-disconnect", action="store_true",
                        help="Release follower torque when this helper exits. "
                             "Default is to keep torque enabled so the arm "
                             "does not sag before the next autonomous process connects.")
    args = parser.parse_args()

    home = load_home(task=args.task)
    if not args.quiet:
        target_label = f"task '{args.task}' start" if args.task else "canonical HOME"
        print(f"Target: {target_label}")

    # Lazy import so help/parse works without opening the serial port.
    from lerobot.robots.so_follower import SO101Follower, SO101FollowerConfig

    robot = SO101Follower(SO101FollowerConfig(
        port=FOLLOWER_PORT,
        id=ROBOT_ID,
        use_degrees=True,
        disable_torque_on_disconnect=args.release_on_disconnect,
        # No max_relative_target here — we ramp manually below to avoid
        # the policy-style relative clip which would slow us excessively.
    ))
    robot.connect()

    try:
        # Read current pose
        obs = robot.get_observation()
        current = {k: float(obs[k]) for k in home}

        if not args.quiet:
            print("Current pose:")
            for k, v in current.items():
                print(f"  {k:20s} = {v:+7.2f}  (target {home[k]:+7.2f})")

        # Linear interpolate from current -> home over `duration` seconds.
        n_steps = max(1, int(args.duration * HZ))
        period = 1.0 / HZ
        for i in range(1, n_steps + 1):
            alpha = i / n_steps
            cmd = {k: current[k] + alpha * (home[k] - current[k]) for k in home}
            robot.send_action(cmd)
            time.sleep(period)

        # Settle: hold final pose for 0.5s so servos finish settling.
        robot.send_action(home)
        time.sleep(0.5)

        if not args.quiet:
            final_obs = robot.get_observation()
            print("\nFinal pose:")
            for k in home:
                print(f"  {k:20s} = {float(final_obs[k]):+7.2f}  (target {home[k]:+7.2f})")
            print("\n[ok] Robot at HOME.")

        return 0
    finally:
        robot.disconnect()


if __name__ == "__main__":
    sys.exit(main())
